# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DynamicAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualAnalyzerAndroid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MD5', models.CharField(max_length=32)),
                ('ENGINES', models.TextField()),
                ('FINISHES', models.TextField()),
                ('HARDCODED', models.TextField()),
                ('DATABASE', models.TextField()),
                ('CONFIG_MANIPULATION', models.TextField()),
                ('SOURCE_MANIPULATION', models.TextField()),
                ('DATABASE_MANIPULATION', models.TextField()),
                ('COMMUNICATION_PLAIN', models.TextField()),
                ('CERT_LOCKED', models.TextField()),
                ('REPLAY', models.TextField()),
                ('TIMEOUT', models.TextField()),
                ('HIJACK', models.TextField()),
                ('MSG_DOS', models.TextField()),
                ('REGISTER', models.TextField()),
                ('LOGIN', models.TextField()),
                ('NETWORK', models.TextField()),
                ('CLOUD_AUTH', models.TextField()),
                ('DEVICE_AUTH', models.TextField()),
                ('DEVICE_CLOUD', models.TextField()),
                ('FIRMWARE_UPDATE', models.TextField()),
                ('FIRMWARE_STORAGE', models.TextField()),
            ],
        ),
    ]
