# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobSF', '0002_auto_20161130_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.TextField()),
                ('TYPE', models.TextField()),
                ('SOURCE', models.TextField()),
                ('EXTRA', models.TextField()),
                ('MD5', models.CharField(max_length=32)),
                ('TS', models.DateTimeField()),
            ],
        ),
    ]
