# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobSF', '0003_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.TextField()),
                ('MEMBER', models.TextField()),
                ('SAMPLE', models.TextField()),
                ('ENGINES', models.TextField()),
                ('PROGRESS', models.IntegerField()),
                ('TS', models.DateTimeField()),
            ],
        ),
    ]
