# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobSF', '0004_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='SAMPLE',
            field=models.CharField(max_length=32),
        ),
    ]
