# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobSF', '0005_auto_20171226_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='SAMPLE',
            new_name='SAMPLEMD5',
        ),
    ]
