# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobSF', '0006_auto_20171226_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='CONSOLES',
            field=models.TextField(default=b''),
        ),
    ]
